### PR TITLE
Input component enhancement and Searchbar component fixes

### LINKED ISSUE #398: Hidden animated label in Input component.
https://github.com/bigbinary/neeto-chat-rn/pull/375#discussion_r942246242

### LINKED ISSUE #416: Styles passed to the Searchbar input aren't getting applied.

### PR DESCRIPTION
**Pull request by Tsudhishnair**
Fixes #398 
Fixes #416

### CODE REVIEW

**Comment by Tsudhishnair** [comment]
@sangameshsomawar _a Please review.

**Comment by Tsudhishnair** [comment]
@sangameshsomawar @jenipharachel  In order to fix the style issue in the Searchbar component, I have made the Input in the searchbar as a styled component instead of refactoring the TextInput component from neeto-ui-rn and using it in the Searchbar component as the former one is the simplest and less complex approach. 
Since TextInput component already uses a ref to handle animation we can't remove it and forward a separate ref from the searchbar component to access the methods like blur, focus etc of the Input component. 

There is one approach with which we can access those methods is by using `useImperativeHandle` to pass the refs, but the issue with that approach is we have to manually add methods like shared below. The drawback of this approach is we have to manually specify the methods in the TextInput component based on the requirement which will make the component more complex.

```  
useImperativeHandle(ref, () => ({
    handleBlur: inputRef.current.onBlur(),
  }));
  ````
  
 So let me know your thoughts if the first fix which I have made currently is good enough or do we have to go with the second approach so that we are using the same TextInput component and don't have to make the Input as a styled component everywhere we need it.

**Comment by jenipharachel** [comment]
@Tsudhishnair @sangameshsomawar  I think we can go with the first approach. Down the lane, just reading the Input component code will become tricky and might require extra development time to make any changes, if we go with the `useImperativeHandle` approach

**Comment by Tsudhishnair** [comment]
Forgot to mention the third approach, which we had already discussed in the standup, is by having the Styled TextInput as it is in the Input component and based on a prop we can toggle between the basic and animated component.

**Comment by sangameshsomawar** [comment]
@Tsudhishnair I think we can go ahead with the current approach.

File: src/components/Input.js [hunk 1]
```diff
@@ -137,12 +137,15 @@ export const Input = props => {
...
-      });
+    {
+      !!label &&
+        inputRef.current &&
+        inputRef.current.setNativeProps({
+          style: {
+            top: isFocused ? 10 : 0,
+          },
+        });
+    }
```
Comment (sangameshsomawar) [inline src/components/Input.js:148]: @Tsudhishnair I think we no need to wrap in curly brackets here, as this code is not in JSX.

**Review by sangameshsomawar — APPROVED** [review]
@Tsudhishnair: Posted a minor comment, please check and merge.

File: src/components/Input.js [hunk 2]
```diff
@@ -137,15 +137,13 @@ export const Input = props => {
...
-        inputRef.current &&
-        inputRef.current.setNativeProps({
-          style: {
-            top: isFocused ? 10 : 0,
-          },
-        });
-    }
+    !!label &&
+      inputRef.current &&
+      inputRef.current.setNativeProps({
```
Comment (sangameshsomawar) [inline src/components/Input.js:142]: @Amaljith-K Here line number 141 and 142 can be written as `inputRef.current?.setNativeProps` with null coalescing operator. Can this be a useful lint rule?

Comment (Amaljith-K) [reply src/components/Input.js:142]: We cannot enforce that via rule because they are not equivalent.
If `str` is an empty string, 
`str && str.at(0)` returns an empty string
`str?.at(0)` returns `undefined`

Since ESLint has no way of knowing types of variables in JS, we cannot enforce that rule.
